; Script generated by the Antigravity IDE.

#define MyAppName "WinCarePro"
#define MyAppVersion "3.4.9"
#define MyAppPublisher "Nguyen-Trung-Tien"
#define MyAppExeName "WinCarePro.exe"

[Setup]
AppId={{C7F40803-B5CE-4EB4-BB24-2D08306EA6E1}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={commonpf}\{#MyAppName}
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
PrivilegesRequired=admin
CloseApplications=force
CloseApplicationsFilter=*.exe
RestartApplications=yes
SuppressMsgBoxes=yes
DirExistsWarning=no
DisableWelcomePage=yes
DisableFinishedPage=yes
OutputDir=PublishOutput
OutputBaseFilename=WinCareProSetup
Compression=lzma2/max
SolidCompression=yes
WizardStyle=modern
SetupIconFile=Assets\AppIcon.ico
UninstallDisplayIcon={app}\{#MyAppExeName}

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "PublishOutputFolder\*"; DestDir: "{app}"; Flags: recursesubdirs createallsubdirs ignoreversion

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; WorkingDir: "{app}"; IconFilename: "{app}\{#MyAppExeName}"; IconIndex: 0
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"; IconFilename: "{app}\{#MyAppExeName}"; IconIndex: 0
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon; WorkingDir: "{app}"; IconFilename: "{app}\{#MyAppExeName}"; IconIndex: 0

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: shellexec nowait postinstall

[UninstallDelete]
Type: filesandordirs; Name: "{userappdata}\{#MyAppName}"
Type: filesandordirs; Name: "{localappdata}\Temp\WinCareIcons"

[Code]
// Refresh Windows Shell icon cache on install/uninstall to ensure taskbar/desktop icons update instantly
procedure SHChangeNotify(wEventId: LongInt; uFlags: UINT; dwItem1: LongInt; dwItem2: LongInt);
  external 'SHChangeNotify@shell32.dll stdcall';

procedure CurStepChanged(CurStep: TSetupStep);
begin
  if CurStep = ssPostInstall then
  begin
    SHChangeNotify($08000000, $0000, 0, 0); // SHCNE_ASSOCCHANGED, SHCNF_IDLIST
  end;
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
begin
  if CurUninstallStep = usPostUninstall then
  begin
    SHChangeNotify($08000000, $0000, 0, 0);
  end;
end;


